### Numpy Array Indexing

In [2]:
import numpy as np

### Andrii

#### Replace NumPy array elements that doesn’t satisfy the given condition

In [42]:
n_arr = np.array([[45.42436315, 52.48558583, 10.32924763],
[5.7439979, 50.58220701, 25.38213418]])
print("Даний масив:")
print(n_arr)

print("Замінити всі елементи масиву, які більше 30. на 7.77 ")
n_arr[n_arr > 30.] = 7.77

print("Новий масив:")
print(n_arr)

Даний масив:
[[45.42436315 52.48558583 10.32924763]
 [ 5.7439979  50.58220701 25.38213418]]
Замінити всі елементи масиву, які більше 30. на 7.77 
Новий масив:
[[ 7.77        7.77       10.32924763]
 [ 5.7439979   7.77       25.38213418]]


#### Return the indices of elements where the given condition is satisfied

In [43]:
# a є масивом цілих чисел. 
a = np.array([[1, 2, 3], [4, 5, 6]])

print(a)

print ('Індекси елементів менших 4 ')

b = np.where(a<4)
print(b)

print("Елементи, які є меншими за 4")
print(a[b])


[[1 2 3]
 [4 5 6]]
Індекси елементів менших 4 
(array([0, 0, 0], dtype=int64), array([0, 1, 2], dtype=int64))
Елементи, які є меншими за 4
[1 2 3]


#### Replace NaN values with average of columns

In [46]:
ini_array = np.array([[1.3, 2.5, 3.6, np.nan],
[2.6, 3.3, np.nan, 5.5],
[2.1, 3.2, 5.4, 6.5]])

# друк початкового масиву.
print ("початковий масив:\n", ini_array)

# заміна nan
res = np.where(np.isnan(ini_array), np.ma.array(ini_array, 
mask = np.isnan(ini_array)).mean(axis = 0), ini_array)

# друк кінцевого масиву.
print ("\nкінцевий масив:\n", res)

початковий масив:
 [[1.3 2.5 3.6 nan]
 [2.6 3.3 nan 5.5]
 [2.1 3.2 5.4 6.5]]

кінцевий масив:
 [[1.3 2.5 3.6 6. ]
 [2.6 3.3 4.5 5.5]
 [2.1 3.2 5.4 6.5]]


### Stas

#### Replace negative value with zero in numpy array

In [22]:
arr=np.array([1,4,-7,8,-11,4,0,-47]) 
arr[arr<0]=0 
arr 

array([1, 4, 0, 8, 0, 4, 0, 0])

#### How to get values of an NumPy array at certain index positions?

In [23]:
arr1=np.array([1,2,3,4,5,6]) 
arr2=np.array([12,87,45]) 
arr1.put([0,2,5],arr2) 
arr1

array([12,  2, 87,  4,  5, 45])

#### Find indices of elements equal to zero in a NumPy array

In [16]:
example = np.array([1, 0, 2, 0, 3, 0, 0, 
                    5, 6, 7, 5, 0, 8])


def zeroes(arr):    
    res = []
    for i in range(len(arr)):
        if arr[i] == 0:
            res.append(i) 
    return res

zeroes(example)

[1, 3, 5, 6, 11]

### Petro

#### How to Remove columns in Numpy array that contains non-numeric values?

In [13]:
example = np.array([[10.5, 22.5, np.nan],
                  [41, 52.5, np.nan]])

cols_filtered = np.isposinf(example).any(axis=0)
cols_filtered
# example[:, cols_filtered]

array([False, False, False])

#### How to access different rows of a multidimensional NumPy array?

In [19]:
arr = np.array([[101, 20, 3, 10], 
                [40, 5, 66, 7], 
                [70, 88, 9, 141]])

def access(rows):
    print(f'{arr=}\nAccessed rows:{arr[rows]}')
    
access(1)

arr=array([[101,  20,   3,  10],
       [ 40,   5,  66,   7],
       [ 70,  88,   9, 141]])
Accessed rows:[40  5 66  7]


#### Get row numbers of NumPy array having element larger than X

In [39]:
arr = np.array([[1, 2, 3, 4, 5],
                  [10, -3, 30, 4, 5],
                  [3, 2, 5, -4, 5],
                  [9, 7, 3, 6, 5] 
                 ])

def get_larger(value):
    rows = (arr > value).any(axis=1)
    return rows
    
arr[get_larger(6)]

array([[10, -3, 30,  4,  5],
       [ 9,  7,  3,  6,  5]])

### Orest

#### Get filled the diagonals of NumPy array

In [27]:
arr = np.array([[1, 2], [2, 1]])
rows, cols = arr.shape


def filler(arr, n):
    for i in range(rows):
        for j in range(cols):
            if i == j:
                arr[i][j] = n
                
filler(arr, 3)
print(arr)

[[3 2]
 [2 3]]


#### Check elements present in the NumPy array

In [ ]:
arr1 = np.array([[1, 2], [3, 4], [5,11]])
arr2 = [1, 4, 6]
arr = np.isin(arr1, arr2)
arr

#### Combined array index by index

In [40]:
arr1 = np.array([1, 3, 5])
arr2 = np.array([7, 9, 11])
arr = np.dstack((arr1, arr2))
arr

array([[[ 1,  7],
        [ 3,  9],
        [ 5, 11]]])